name: tax_retribution_app
description: Aplikasi Pelaporan Retribusi Pajak dengan MVVM Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  # Provider digunakan untuk manage state di seluruh aplikasi
  provider: ^6.1.1

  # HTTP Client
  # Untuk melakukan HTTP requests ke API
  http: ^1.1.2

  # Local Storage
  # Untuk menyimpan data sederhana seperti user preferences
  shared_preferences: ^2.2.2
  
  # Secure Storage
  # PENTING: Untuk menyimpan token & data sensitif dengan enkripsi
  flutter_secure_storage: ^9.0.0

  # Biometric Authentication
  # Untuk login dengan fingerprint & face ID
  local_auth: ^2.1.8

  # Device Information
  # Untuk mendapatkan device ID & info device
  device_info_plus: ^10.0.1

  # Date & Currency Formatting
  # Untuk format tanggal dan mata uang Indonesia
  intl: ^0.19.0

  # Environment Variables
  # Untuk manage API URLs & secrets
  flutter_dotenv: ^5.1.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter untuk code quality
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - .env
  #   - assets/images/
  #   - assets/icons/

  # Fonts (Optional - bisa pakai custom font)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
